name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use

    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t docker:latest .
        docker tag docker:latest saiswetha07/my_docker_repo:v1
        docker push saiswetha07/my_docker_repo:v1
